#ifndef PARAMETRE_H_
#define PARAMETRE_H_

#define TAILLE_DEFAULT_X 400
#define TAILLE_DEFAULT_Y 400
#define TAILLE_MIN_X 100
#define TAILLE_MIN_Y 100

#define TYPE_DEFAULT_MESH "cube.obj"
#define TAILLE_DEFAULT_VAISSEAU 0.2
#define POSX_DEFAULT_VAISSEAU 0
#define POSY_DEFAULT_VAISSEAU 0
#define POSZ_DEFAULT_VAISSEAU 0
#define ANGLEX_DEFAULT_VAISSEAU 0
#define ANGLEY_DEFAULT_VAISSEAU 0
#define ANGLEZ_DEFAULT_VAISSEAU 0

#endif