#ifndef PARAMETRE_H_
#define PARAMETRE_H_

#define TAILLE_DEFAULT_X 400
#define TAILLE_DEFAULT_Y 600
#define TAILLE_MIN_X 100
#define TAILLE_MIN_Y 150

#define TYPE_DEFAULT_MESH "cube.obj"
#define TAILLE_DEFAULT_VAISSEAU 0.1
#define POSX_DEFAULT_VAISSEAU 0
#define POSY_DEFAULT_VAISSEAU 0
#define POSZ_DEFAULT_VAISSEAU 0
#define ANGLEX_DEFAULT_VAISSEAU 0
#define ANGLEY_DEFAULT_VAISSEAU 0
#define ANGLEZ_DEFAULT_VAISSEAU 0
#define VELOCITYX_DEFAULT_VAISSEAU 0
#define VELOCITYY_DEFAULT_VAISSEAU 0
#define VELOCITYZ_DEFAULT_VAISSEAU 0
#define ACCELERATIONX_DEFAULT_VAISSEAU 0
#define ACCELERATIONY_DEFAULT_VAISSEAU 0
#define ACCELERATIONZ_DEFAULT_VAISSEAU 0
#define TRAJECTORY_DEFAULT_FILE_NAME ""

#define STRUCT_POSITION_DEF {0,0,0}
#define STRUCT_ROTATION_DEF {0,0,0}
#define STRUCT_VELOCITY_DEF {0,0,0}
#define STRUCT_ACCEL_DEF {0,0,0}

#define INTERVALE_TEMP_SHOOT 10 // temp = X*20ms ex: 50*20 = 1s
#define VELOCITY_BOULET 6
#define TAILLE_BOULET 0.03
#define INTERVALE_TEMP_ENEMY 100  // provisoire


#define NB_KEYS 8
#define T_ECHAP 0
#define T_GAUCHE 1
#define T_HAUT 2
#define T_DROITE 3
#define T_BAS 4
#define T_CTRL 5
#define T_SHIFT 6
#define T_SPACE 7

#endif